BMC/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.urls import path, include

app_name = 'BMC'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('a/', include('account.urls', namespace='account_app')),
    url(r'^', include('book.urls'), name='book_app'),
    url(r'^notifications/', include('notifications.urls', namespace='notifications_app')),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""BMC URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

notifications/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views


app_name = 'notifications_app'

urlpatterns = [
    path('', views.notifications_list, name='home'),
    url(r'^n-l/$', views.notifications_loader, name="notifications-loader"),
]

notifications/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType, ContentTypeManager
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.dispatch import Signal
from django.db.models.signals import (
    post_save, pre_save, post_delete, pre_delete,
    post_init, pre_init, post_migrate, pre_migrate, m2m_changed
)

from account.models import ProfileModel
from book.models import BookModel, BookCommentModel

level_choices = [
    ('info', 'Info',),
    ('warning', 'Warning',),
    ('success', 'Success',),
    ('permission', 'Permission',),
]


def add_notification_to_followers(actor, type, notification_pk, target=None):
    notification = get_object_or_404(NotificationModel, pk=notification_pk)
    if type == "comment":
        user_notification = get_object_or_404(UserNotificationModel, user=actor)
        if user_notification.user != actor:
            user_notification.unread_notifications.add(notification)
        else:
            pass
    elif type == "lecture":
        profile = get_object_or_404(ProfileModel, user=actor)
        for follower in profile.follow.all():
            qs = UserNotificationModel.objects.get_or_create(
                user=follower
            )
            follower_notification = get_object_or_404(UserNotificationModel, user=follower)
            follower_notification.unread_notifications.add(notification)
    elif type == "follow":
        qs = UserNotificationModel.objects.get_or_create(
            user=target
        )
        uploader = get_object_or_404(UserNotificationModel, user=target)
        uploader.unread_notifications.add(notification)
    else:
        model = get_object_or_404(ProfileModel, user=actor)
        for user in model.follow.all():
            user_notification = get_object_or_404(UserNotificationModel, user=user)
            user_notification.unread_notifications.add(notification)


class NotificationModel(models.Model):
    level = models.CharField(choices=level_choices, blank=True, max_length=100, default=level_choices[0])
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='notifications')
    message = models.TextField(max_length=50)
    link = models.URLField(blank=True)
    description = models.TextField(blank=True, null=True)
    actor_object_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    actor_object_id = models.CharField(max_length=255, null=True)
    actor_content_object = GenericForeignKey("actor_object_content_type", "actor_object_id")
    target_object_content_type = models.ForeignKey(ContentType, null=True, on_delete=models.CASCADE, related_name='target')
    target_object_id = models.CharField(max_length=255, null=True)
    target_content_object = GenericForeignKey('target_object_content_type', 'target_object_id')
    unread = models.NullBooleanField(default=True, blank=True)
    emailed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-timestamp']

    def get_absolute_url(self, **kwargs):
        return reverse("notifications_app:home")

    def read_notification(self):
        self.read = True
        self.save()


class UserNotificationModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    unread_notifications = models.ManyToManyField(NotificationModel, blank=True, related_name='unread_notifications')
    read_notifications = models.ManyToManyField(NotificationModel, blank=True, related_name='read_notifications')
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


def create_notification_by_comment(sender, instance, *args, **kwargs):
    if instance is not None:
        new_notification = NotificationModel(
            user=instance.user,
            link=instance.book.get_absolute_url(),
            message="commented on your book",
            target_content_object=instance,
            actor_content_object=instance.user,

            description="some description",
            unread=True,
            emailed=False,
        )
        new_notification.save()
        add_notification_to_followers(instance.book.user, "comment", new_notification.id)
    else:
        return None


def create_user_notification_for_new_users(sender, instance, *args, **kwargs):
    if instance:
        qs = UserNotificationModel.objects.filter(user=instance).exists()
        if qs is False:
            notification = UserNotificationModel.objects.create(user=instance)
    else:
        pass


post_save.connect(create_user_notification_for_new_users, sender=User, weak=False)
post_save.connect(create_notification_by_comment, sender=BookCommentModel, weak=False)

notifications/views.py
import html
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.views.generic import ListView, View, UpdateView, DeleteView, RedirectView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionDenied
from django.core.exceptions import PermissionDenied, ValidationError
from account.models import ProfileModel
from tools.utils import context, get_authenticated_user_objects, get_session_objects
from notifications.models import NotificationModel, UserNotificationModel
from django.contrib.auth.models import User
nothing_json = HttpResponse(json.dumps("None"), content_type="application/json")
nothing_html = HttpResponse(html.escape("None"), content_type="application/html")


@login_required
def notifications_list(request):
    get_authenticated_user_objects(request)
    notifications = get_object_or_404(UserNotificationModel, user=request.user)
    if notifications.unread_notifications.count() > 0:
        x = notifications.unread_notifications.count()
        for item in notifications.unread_notifications.all():
            notifications.unread_notifications.remove(item)
            notifications.read_notifications.add(item)
    else:
        x = 8
    context['notifications'] = notifications.read_notifications.all()[:x]
    # very important note: slicing to profiles from previous view my force some profile picture to
    # disappear so need to rewrite it.
    context['profiles'] = ProfileModel.objects.all()
    return render(request, 'notifications/list.html', context)


def notifications_loader(request):

    count = request.POST.get("objectsCount")
    load_count = request.POST.get("loadCount", None)
    if load_count is not None and int(load_count) > 0:
        increment = int(load_count)
    else:
        increment = 3
    if int(count) < 1:
        count = 3
    y = int(count)
    x = y + increment
    if request.is_ajax() and request.method == "POST":
        notifications = get_object_or_404(UserNotificationModel, user=request.user)
        if notifications.unread_notifications.count() > 0:
            for n in notifications.unread_notifications.all():
                notifications.unread_notifications.remove(n)
                notifications.read_notifications.add(n)
        objects = notifications.read_notifications.all()
        context["notifications"] = objects[y:x]
        return render(request, "notifications/notifications-queryset.html", context)
    else:
        return nothing_html

templates/notifications/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block body %}
    <style>
    .single-notification-container:hover{
        text-decoration: none;
    }
    .card-body:hover {
        color:black;
        background-color: #f2f879;
    }
    </style>
    <div class="main-notifications-container" id="main_notifications_container_id">
    {% for item in notifications %}
            {% include "notifications/single-notification-base-container.html" %}
    {% endfor %}
    </div>
    <div class="main-objects-container" id="main_notifications_loader_container_id" {% if total_notifications <= 8 %}style="display:none;" {% endif %}>
        {% include "general/objects-loader-base-container.html" %}
    </div>
    <div class="scripts-container">
        <script>
            var __notifications_loader_url__ = "{% url 'notifications_app:notifications-loader' %}";
            $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}'}});
            var csrf_token = "{{ csrf_token }}";
        </script>
        <input type="hidden" id="total_notifications_id" value="{{ total_notifications }}">
        <script src="{% static 'js/notifications.js' %}"></script>
    </div>
{% endblock %}

templates/notifications/notifications-queryset.html
{% for item in notifications %}
        {% include "notifications/single-notification-base-container.html" %}
{% endfor %}

templates/notifications/single-notification-base-container.html
{% load i18n %}
{% load class_name %}
<a href="{{ item.link }}" style="color:black;" class="single-notification-container" id="{{ item.pk }}_single_notification_container_id">
    <div class="card" style="margin-bottom:3px;">
    <div class="card-body" >
        <div class="picture-container" style="display: inline-block;">
            {% if item.actor_content_object|class_name == "User" %}
                {% for profile in profiles %}
                    {% if profile.user == item.actor_content_object %}
                        <img  {% if profile.picture %} src="{{ profile.picture.url }}" {% else %} src="{{ profile.picture_cdn }}" {% endif %} class="responsive-circle-45" />
                        <span class="user-container responsive-text-13">
                            {{ item.actor_content_object.get_full_name }}
                        </span>
                    {% endif %}
                {% endfor %}
            {% else %}
                <strong class="responsive-text-15">{{ item.actor_content_object }}</strong>
            {% endif %}
        </div>
        <span class="action-container responsive-text-13">{{ item.message }}</span>
        <span class="timestamp-container responsive-text-10" >
            {% if item.timestamp.date > comparing_time %}
                ({{ item.timestamp|timesince }} {% trans 'ago' %})
            {% else %}
                {{ item.timestamp.date  }}
            {% endif %}
        </span>
    </div>
    </div>
</a>