BMC/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.urls import path, include

app_name = 'BMC'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('a/', include('account.urls', namespace='account_app')),
    url(r'^', include('book.urls'), name='book_app'),
    url(r'^notifications/', include('notifications.urls', namespace='notifications_app')),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""BMC URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

book/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from book import views
from tools import utils
app_name = 'book_app'

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'^book_view=(?P<slug>[-\w]+)$', views.book_detail, name='book_detail'),
    url(r'^tags=(?P<slug>[-\w]+)$', views.view_by_tags, name='tags-view'),
    url(r'^category=(?P<category>[-\w]+)$', views.view_by_category, name='categories-view'),
    url(r'^book_view=(?P<slug>[-\w]+)/d/$', views.book_delete, name='book-delete'),
    url(r'^book_view=(?P<slug>[-\w]+)/e/$', views.book_edit, name='book-update'),
    url(r'^ajax-book-update/$', views.book_edit, name='ajax-book-update'),
    url(r'^liked_books$', views.liked_books, name='liked-books'),
    url(r'^upload$', views.book_upload, name='book-upload'),

    url(r'^change-thumbnail/$', views.book_cover_update, name='change-thumbnail'),
    url(r'^change-thumbnail/$', views.book_cover_update, name='change-thumbnail'),
    url(r'^general-object-delete/$', views.book_delete, name="general-object-delete"),
    url(r'^object-like-toggle/$', utils.object_like_toggle, name="object-like-toggle"),
    url(r'^object-dislike-toggle/$', utils.object_dislike_toggle, name="object-dislike-toggle"),
    url(r'^general-objects-loader/$', utils.objects_loader, name="general-objects-loader"),

    url(r'^comment-like-toggle/$', utils.general_comment_like_toggle, name='comment-like-toggle'),
    url(r'^comment-dislike-toggle/$', utils.general_comment_dislike_toggle, name='comment-dislike-toggle'),
    url(r'^general-comment-delete/$', utils.general_comment_delete, name='general-comment-delete'),
    url(r'^get-comment-form/$', utils.get_comment_form, name='get-comment-form'),
    url(r'^save-comment-changes/$', utils.save_comment_update, name='save-comment-changes'),
    url(r'^comment-counts/$', utils.get_comments_count, name='comments-count'),
    url(r'^general-comment-add/$', utils.general_comment_add, name='general-comment-add'),
    url(r'^general-comments-sorts/$', utils.general_comments_sort_or_load, name='general-comments-sort'),
    url(r'^general-comments-load/$', utils.general_comments_sort_or_load, name='general-comments-load'),

    url(r'^o-d-i/$', utils.object_download_count_increment, name='download-increment'),
    url(r'^o-v-i/$', utils.object_views_count_increment, name='views-increment'),
    url(r'^t-v-i/$', utils.tags_views_count_increment, name='tags-views-inc'),
    url(r'^tags-create/$', utils.tags_create, name="tags-create"),
    url(r'^add-tags-model/$', utils.add_tags_to_model, name="tags-to-model"),
    url(r'^u-f-t/$', utils.uploader_follow_toggle, name="uploader-follow-toggle"),

    url(r'^c-n-sp-sh/$', utils.create_spreadsheet, name="create-spreadsheet"),
    url(r'^spreadsheets-loader/$', utils.spreadsheets_loader, name="spreadsheets-loader"),
    url(r'^contributors-toggle/$', utils.contributors_toggle, name="contributors-toggle"),

    url(r'^(?P<username>[-\w]+)/spreadsheet=(?P<slug>[-\w]+)$', views.spreadsheet_detail, name='spreadsheet-detail'),
    url(r'^spreadsheet=(?P<slug>[-\w]+)/del/$', views.spreadsheet_delete, name='spreadsheet-delete'),
    url(r'^spreadsheet=(?P<slug>[-\w]+)/edit/$', views.spreadsheet_edit, name='spreadsheet-edit'),
    url(r'^(?P<username>[-\w]+)/spreadsheets$', views.spreadsheets_view, name='spreadsheets'),

    url(r'^spreadsheet=(?P<slug>[-\w]+)/lecture=(?P<lecture_id>[0-9]+)$', views.lecture_detail, name='lecture-detail'),
    url(r'^lecture=(?P<id>[0-9]+)/edit/$', views.lecture_edit, name='lecture-edit'),
    url(r'^lecture=(?P<id>[0-9]+)/del/$', views.lecture_delete, name='lecture-delete'),
    url(r'^lecture-create-ajax$', views.create_lecture, name='lecture-create'),

    url(r'^doctor/id=(?P<id>[0-9]+)/$', views.doctor_detail, name='doctor-detail'),

]

book/models.py
from django.utils.translation import ugettext as _
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from django.db.models import Q
from tools.categories import book_category, general_category, material_list
from tools.unique_url import random_unique_chars_digit_slug_generator
from datetime import datetime, time, timedelta, date


class CommentsManager(models.Manager):
    def sliced(self):
        return super(CommentsManager, self).all()[:5]


class BookManager(models.Manager):
    def search(self, query, category=None, type=None):
        if query and category == "General":
            qs = super(BookManager, self).filter(
                Q(description__icontains=query) |
                # Q(tags__icontains=query) |
                Q(title__icontains=query) |
                Q(user__username__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__contains=query)
            ).distinct()
            return qs
        elif query is not None and category != 'General':

            qs = super(BookManager, self).filter(
                Q(description__icontains=query) and Q(category__contains=category) |
                Q(tags__icontains=query) and Q(category__contains=category) |
                Q(title__icontains=query) and Q(category__contains=category) |
                Q(user__username__icontains=query) and Q(category__contains=category) |
                Q(user__first_name__icontains=query) and Q(category__contains=category) |
                Q(user__last_name__icontains=query)and Q(category__contains=category)
            ).distinct()
            return qs
        else:
            return None


class LectureManager(models.Manager):
    def search(self, query, material="General"):
        if query and material == "General":
            qs = super(LectureManager, self).filter(
                Q(comment__icontains=query) |
                Q(title__icontains=query) |
                Q(doctor__icontains=query) |
                Q(links__title__icontains=query)
            ).distinct()
            return qs

        elif query is not None and material != 'General':
            qs = super(LectureManager, self).filter(
                Q(comment__icontains=query) and Q(material__contains=material) |
                Q(title__icontains=query) and Q(material__contains=material) |
                Q(doctor__icontains=query) and Q(material__contains=material) |
                Q(links__title__icontains=query) and Q(material__contains=material)
            ).distinct()
            return qs
        else:
            return None

    def filter_by_date(self, material, from_date, to_date, *args, **kwargs):
        if material and from_date and to_date:

            s_year, s_month, s_day = from_date.split("-")
            e_year, e_month, e_day = to_date.split("-")
            start_date = datetime.combine(date(int(s_year), int(s_month), int(s_day)), time())
            end_date = datetime.combine(date(int(e_year), int(e_month), int(e_day)), time())
            qs = super(LectureManager, self).filter(timestamp__range=(start_date, end_date)).filter(
                material__exact=material
            )
            print("filter by date", qs)
            return qs
        else:
            pass


class BookTagsModel(models.Model):
    title = models.CharField(max_length=150, unique=False, db_index=True)
    slug = models.SlugField(_('Slug'), max_length=255, blank=True, unique=False)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    views = models.BigIntegerField(default=0, blank=True, null=True)
    type = models.CharField(max_length=10, null=True, blank=True, default="bk")
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title, allow_unicode=True)
        super(BookTagsModel, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_app:tags-view", kwargs={"slug": self.slug})


class BookModel(models.Model):
    title = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books")
    slug = models.SlugField(blank=True, editable=False, unique=True)
    like = models.ManyToManyField(User, related_name='book_likes', blank=True)
    dislike = models.ManyToManyField(User, related_name='book_dislike', blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to='books/cover')
    thumbnail_cdn = models.TextField(null=True, blank=True)
    file = models.FileField(blank=True, null=True, upload_to="books/pdf/")
    file_cdn = models.TextField(blank=True, null=True)
    category = models.CharField(max_length=100, choices=book_category, default='General')
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(BookTagsModel, related_name='tags', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)  # auto_now_add for creation date
    update = models.DateTimeField(auto_now=True)  # auto_now for update
    views = models.BigIntegerField(default=0, blank=True)
    share = models.BigIntegerField(default=0, blank=True)
    download = models.PositiveIntegerField(default=0, blank=True, null=True)
    download_link_1 = models.TextField(blank=True, null=True)
    download_link_2 = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=5, null=True, blank=True, default='bk')
    objects = models.Manager()
    manager = BookManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id', '-timestamp']

    def get_absolute_url(self):
        return reverse("book_app:book_detail", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("book_app:book-update", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("book_app:book-delete", kwargs={"slug": self.slug})

    def get_profile_url(self):
        return reverse("account_app:profile", kwargs={'username': self.user.username})


class BookCommentModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commentsmodel_set')
    slug = models.SlugField(blank=True, null=True, editable=False, unique=True)
    book = models.ForeignKey(BookModel, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField(max_length=1000)
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    dislike = models.ManyToManyField(User, related_name='dislikes', blank=True)
    type = models.CharField(max_length=5, null=True, blank=True, default='bk')
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    objects = CommentsManager()

    def get_profile_url(self):
        return reverse("account_app:profile", kwargs={'username': self.user.username})


class SpreadsheetModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='spreadsheets')
    slug = models.SlugField(blank=True, null=True, editable=False, unique=True)
    title = models.CharField(max_length=1000, blank=True, null=True)
    description = models.TextField(max_length=1000, blank=True, null=True)
    contributors = models.ManyToManyField(User, related_name='contributors', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    views = models.BigIntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_profile_url(self):
        return reverse("account_app:profile", kwargs={'username': self.user.username})

    def get_absolute_url(self):
        return reverse("book_app:spreadsheet-detail", kwargs={'username': self.user.username, 'slug': self.slug})


doctor_img_cdn = (
    ("/static/img/cdn/doctor-male.jpg", "Male"), ("/static/img/cdn/doctor-female.jpg", "Female")
)


class DoctorModel(models.Model):
    first_name = models.CharField(max_length=225)
    last_name = models.CharField(max_length=225, blank=True, null=True)
    surname = models.CharField(max_length=225, blank=True, null=True)
    picture = models.ImageField(blank=True, null=True)
    picture_cdn = models.CharField(choices=doctor_img_cdn, max_length=1000, blank=True, null=True)
    gender = models.CharField(choices=(("Male", "Male"), ("Female", "Female")), max_length=1000, default=1)
    description = models.TextField(max_length=1000, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    facebook = models.CharField(blank=True, null=True, max_length=10000)
    phone_no = models.IntegerField(blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("book_app:doctor-detail", kwargs={"id": self.id})

    def __str__(self):
        if self.last_name:
            second_name = self.last_name
            if self.surname:
                second_name = self.last_name + ' ' + self.surname
        elif self.surname:
            second_name = self.surname
            if self.last_name:
                second_name = self.last_name + ' ' + self.surname
        else:
            second_name = ""
        full_name = self.first_name + ' ' + second_name
        return full_name


class LectureModel(models.Model):
    material = models.CharField(choices=material_list, default=material_list[0], max_length=100)
    doctor = models.ForeignKey(DoctorModel, related_name='lectures', on_delete=False)

templates/book/book-edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans 'Update' %}{% endblock %}
{% block body %}
<div class="main-container col-lg-6 col-sm-12" style="margin:auto;padding:0px;">
    <div class="card bg-primary responsive-text-15" style="padding:8px;color:white;">
        <span class="responsive-text-15"><span class="fa fa-edit"></span> {% trans "Book Edit" %}</span>
    </div>
    <div class="card bg-basic" id="book-share-section"  >
        <div class="main-book-form-container">
            <div class="card-body" id="card_body_id">
                <div class="loader-container" style="display:none;" id="loader_container_id">
                    <div style="display: flex;justify-content: center;">
                        <img src="{% static 'img/loaders/loader-circle-1.gif' %}" id="img_loader_id"  style="display:inline-block;margin-top:35px;height:50px;width:50px;">
                    </div>
                    <div style="display: flex;justify-content: center;margin-top:20px;">
                        <span class="responsive-text-15" style="display: inline-block;">{% trans 'Please wait' %}</span>
                    </div>
                </div>
                <div class="inputs-container" id="main_book_form_container_id" >
                    <img id="img_id" class="responsive-square-120" {% if book.thumbnail %}src="{{ book.thumbnail.url }}" {% else %}src="{{ book.thumbnail_cdn }}"{% endif %} style="max-height:120px;max-width:120px;border:1px outset silver;border-radius:3px;display:block">
                    <div class="file-input-container" style="margin-bottom:15px;color:white;padding:5px;display:flex; justify-content: center;background:blue;margin-top:10px;border-radius:3px;border:1px outset silver; height:30px; width:100px; ">
                        <span style="position: absolute;" class="fa fa-edit"></span>
                        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                            <input onchange="validFileInput()" style="opacity: 0;" type="file" name="thumbnail" accept="image/jpeg, image/jpg, image/png" id="id_thumbnail">
                        </form>
                    </div>
                    <div class="form-container" style="margin-top:15px;">
                        <form method="post" onsubmit="preventBookUpdateFormEvents(event)" enctype="multipart/form-data" action="">{% csrf_token %}
                            <div class="forms-container" id="forms_container_id">
                                {% for field in book_form %}
                                    {% if field.name != "thumbnail" %}
                                        {% include "general/form-template.html" %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="tags-container"  id="main_tags_container_id">
                                {% include "general/main-tags-create-container.html" %}
                            </div>
                            <div class="btns-container" style="margin-top:15px;">
                                <div class="btn-group d-flex">
                                    <button id="upload_btn_id" type="submit" class="btn btn-primary w-100 responsive-text-15">
                                        <span class="fa fa-save"></span> {% trans 'Save' %}
                                    </button>
                                    <button type="reset" id="cancel_btn_id" class="btn btn-default w-100 responsive-text-15">
                                        <span class="fa fa-times"></span>
                                        {% trans 'Cancel' %}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fake-elms-container">
    <input type="hidden" value="{{ book.slug }}" id="book_slug_id">
    <input type="hidden" id="book_form_id">
</div>
<div class="scripts-container">
    {% include "general/general-urls-container.html" %}
    {% include "book/includes/book-form-urls-container.html" %}
    <script src="{% static 'js/general_javascript-101.js' %}"></script>
    <script src="{% static 'js/book-form-0111.js' %}"></script>
</div>
{% endblock %}

templates/book/book_delete.html
{% extends 'base.html' %}
{% block body %}
{% load i18n %}

<div class="col-xs-12 col-lg-8"  style="padding:0px;margin: auto;">
<div class="card">
    <div class="card-header bg-danger" >
        <h4>{% trans 'You are going to delete your Book, and that is not undo' %}.</h4>
    </div>
    <div class="card-body">
        <p >{% trans 'Are you sure you want to delete this Book' %}:</p>
        <div class="img-container">
             <a href="{{ book.get_absolute_url }}">{{ book.title }}</a><br>
            <img {% if book.thumbnail %}src="{{ book.thumbnail.url }}" {% else %}src="{{ book.thumbnail_cdn }}"{% endif %} class="responsive-square-120"  style="border:1px outset silver;border-radius:5px;object-fit: cover;"/>
        </div>
        <p>{% trans 'If you still want to delete this book click delete or otherwise click cancel' %} </p>
        <form method="post" action="" enctype="multipart/form-data"> {% csrf_token %}
            <div class="btn-group">
                <button type="submit" class="btn btn-danger">
                    <span class="fa fa-trash"></span>
                    {% trans 'Delete' %}
                </button>
                <a class="btn btn-primary" href="{{ book.get_absolute_url }}">
                    <span class="fa fa-window-close"></span>
                    {% trans 'Cancel' %}
                </a>
            </div>
      </form>
    </div>
</div>
</div>
{% endblock %}

templates/book/book_upload.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans 'Upload' %}{% endblock %}
{% block body %}
    <div class="col-lg-6 col-sm-12" style="padding:0px;margin: auto">
        <div class="card bg-primary" style="padding:8px;color:white;">
            <span class="responsive-text-15" style="display: inline">
                 <span class="fa fa-upload"></span> {% trans 'Upload' %}     {% trans 'Book' %}
            </span>
        </div>
        {% include 'book/includes/book-form-section.html' %}
    </div>
    <div class="fake-elms-container">
        <input type="hidden" value="{{ book.slug }}" id="book_slug_id">
    </div>
    <div class="scripts-container">
        {% include "general/general-urls-container.html" %}
        {% include "book/includes/book-form-urls-container.html" %}
        <script src="{% static 'js/general_javascript-101.js' %}"></script>
        <script src="{% static 'js/book-form-0111.js' %}"></script>
    </div>
{% endblock %}

templates/book/lecture-delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head %}
    <title>{% block title %}{{ object.title }}{% endblock %}</title>
{% endblock %}
{% block body %}
    <div class="main-container">
        <div class="main-objects-container">
            <div  class="single-object-container" >
                <div class="card">
                    <div class="card-header bg-danger">
                        <strong class="responsive-text-16">{% trans 'Confirm Delete' %}</strong>
                    </div>
                    <div class="card-body" >
                        <div class="text-container">
                            <strong class="responsive-text-16" >
                                {% trans 'Are you sure that you want to delete this Lecture' %}
                                <a href="{% url 'book_app:lecture-detail' slug=object.spreadsheet.slug lecture_id=object.id %}">
                                    {{ object.title }}
                                </a>?
                            </strong><br>
                        </div>
                        <div class="buttons-container" style="display: block;margin-top:15px;">
                            <form method="post" action="">{% csrf_token %}
                                <div class="btn-group d-flex">
                                    <button type="submit" class="btn btn-primary responsive-text-15 w-100">
                                        <span class="fa fa-trash"></span>
                                        <span class="responsive-text-15">{% trans 'Delete' %}</span>
                                    </button>
                                    <a href="{{ object.spreadsheet.get_absolute_url }}" class="btn btn-danger  w-100 responsive-text-15">
                                        <span class="fa fa-times"></span>
                                        <span class="responsive-text-15">{% trans 'Cancel' %}</span>
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/book/lecture-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block head %}
    <title>{% block title %}{{ object.title }}{% endblock %}</title>
{% endblock %}
{% block body %}
    <div class="main-container col-lg-8" style="padding:0; margin: auto;">
        <div class="main-objects-container" id="main_objects_container_id">
            <div  class="single-object-container" id="{{ object.slug }}_single_object_container_id" style="text-decoration:none;margin-bottom:10px;display:block;color:black;">
                <div class="card">
                    <div class="card-body" style="padding:10px;display:block;">
                        <div class="book-title-container" style="display: block;">
                            <strong class="responsive-text-16" >{% trans 'Lecture' %}: {{ object.title }}</strong>
                        </div><hr>{% if request.user == object.spreadsheet.user or request.user in object.spreadsheet.contributors.all %}
                        <div class="buttons-container">
                            <div class="btn-group">
                                <a href="{% url 'book_app:lecture-edit' id=object.id %}" class="btn btn-primary responsive-text-15">
                                    <span class="fa fa-edit"></span>
                                    <span class="responsive-text-15">{% trans 'Edit' %}</span>
                                </a>{% if request.user == object.spreadsheet.user %}
                                <a href="{% url 'book_app:lecture-delete' id=object.id %}" class="btn btn-danger responsive-text-15">
                                    <span class="fa fa-trash"></span>
                                    <span class="responsive-text-15">{% trans 'Delete' %}</span>
                                </a>{% endif %}
                            </div>
                        </div><hr>{% endif %}
                        <div class="doctor-container responsive-text-15" style="display: block">
                            <strong>{% trans 'Doctor' %}: </strong>
                            <a href="{{ object.doctor.get_absolute_url }}">{{ object.doctor }}</a>
                        </div>
                        <div class="doctor-container  responsive-text-15" >
                            <strong>{% trans 'Material' %}:</strong>  {{ object.material }}
                        </div>
                        <div class="timestamp-container  responsive-text-15" >
                            <strong>{% trans 'Published on' %}:</strong>  {{ object.timestamp|date:"d/ m/ Y" }} ( {{ object.timestamp|timesince }} {% trans 'ago' %})
                        </div>
                        <div class="update-container  responsive-text-15" >
                            <strong>{% trans 'Last update' %}:</strong>  {{ object.update|date:"d/ m/ Y" }} ( {{ object.update|timesince }} {% trans 'ago' %})
                        </div>
                        <div class="update-container  responsive-text-15" >
                            <strong>{% trans 'Views' %}:</strong>  {{ object.views }}
                        </div>
                        <div class="spreadsheet-container  responsive-text-15">
                            <strong>{% trans 'Spreadsheet' %}:</strong> <a href="{{ object.spreadsheet.get_absolute_url }}">{{ object.spreadsheet }}</a>
                        </div>
                        <div class="share-link-container">
                                <strong class="responsive-text-15">{% trans "Share link for social medial (copy and paste)" %}:</strong>
                                <button style="padding:0 3px 0 3px;" onclick="copySharingLink()" class="btn btn-dark responsive-text-14" type="button" >
                                    <span class="fa fa-copy"></span> {% trans 'Copy to clipboard' %}
                                </button>
                                <input hidden id="sharing_link_input_id" title="{% trans 'Copy the link for share' %}" value="{{ request.build_absolute_uri }}"/>
                        </div>
                        {% if object.comment %}
                        <div class="comment-container  responsive-text-15" style="background-color: #f3f3f3;color:black;border-radius:5px;border:1px outset silver;padding:10px;margin-top:10px;">
                            <strong>{% trans 'Comment' %}:</strong><br>
                            {{ object.comment|linebreaksbr|urlizetrunc:30 }}
                        </div>{% endif %}
                        {% if object.file %}
                            <div class="file-container  responsive-text-15" style="background-color: #f3f3f3;color:black;border:1px outset silver;padding:10px;margin-top:10px;">
                                <strong>{% trans 'Lecture File' %}:</strong><br>
                                {% trans 'File size' %}: {{ object.file.size|filesizeformat }}
                                {% if file_mimetype == "application/pdf" %}
                                    <iframe src="{{ object.file.url }}" style="overflow-x:hidden;height:500px;width:100%;"></iframe>
                                 {% else %}
                                    <a class="btn btn-primary responsive-text-15" href="{{ object.file.url }}" style="padding:0 5px 0 5px;">
                                       <span class="fa fa-download"></span> {% trans 'Download' %}</a>
                                 {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="fake-elm-container">
        <input type="hidden" id="object_type_id" value="lr">
        <input type="hidden" id="view_inc_type_id" value="lr">
        <input type="hidden" id="parent_slug_id" value="{{ object.id }}">
    </div>
    <div class="scripts-container">
        {% include 'book/includes/book-main-urls-container.html' %}
        <script >
            window.addEventListener("load", setViewsIncrement);
            function setViewsIncrement() {
                var type = document.getElementById("object_type_id").value;
                var parent_slug = document.getElementById("parent_slug_id").value;
                objectViewsIncrement(type, parent_slug);

            }
            function objectViewsIncrement(type, parent_slug){
                $.ajax({
                    url: __object_views_increment_url__,
                    dataType: "json",
                    data: {"parent_slug": parent_slug, "type": type},
                    type: "POST",
                    success:function (data) {
                        // do nothing..
                    },
                    error:function (xhr, status, err) {
                        console.log("xhr: "+ xhr + ", status: " + status + ", err: " + err);
                    }
                });

            }
        </script>
    </div>
{% endblock %}