BMC/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.urls import path, include

app_name = 'BMC'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('a/', include('account.urls', namespace='account_app')),
    url(r'^', include('book.urls'), name='book_app'),
    url(r'^notifications/', include('notifications.urls', namespace='notifications_app')),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""BMC URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

account/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views


app_name = 'account_app'

urlpatterns = [
    url(r'^uploaders/$', views.uploaders_view, name='uploaders'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^settings/$', views.account_edit, name='account-edit'),
    url(r'^account-delete$', views.account_delete, name='account-delete'),
    url(r'^password-change$', views.password_change, name='password-change'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/$', views.RegistrationView.as_view(), name="register"),
    url(r'^(?P<username>[-\w]+)$', views.ProfileView.as_view(), name='profile'),

    # url(r'^account-edit/$', views.user_info_change, name='account-edit'),
    # url(r'^password-change/$', views.password_change, name='password-change'),

]

book/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from book import views
from tools import utils
app_name = 'book_app'

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'^book_view=(?P<slug>[-\w]+)$', views.book_detail, name='book_detail'),
    url(r'^tags=(?P<slug>[-\w]+)$', views.view_by_tags, name='tags-view'),
    url(r'^category=(?P<category>[-\w]+)$', views.view_by_category, name='categories-view'),
    url(r'^book_view=(?P<slug>[-\w]+)/d/$', views.book_delete, name='book-delete'),
    url(r'^book_view=(?P<slug>[-\w]+)/e/$', views.book_edit, name='book-update'),
    url(r'^ajax-book-update/$', views.book_edit, name='ajax-book-update'),
    url(r'^liked_books$', views.liked_books, name='liked-books'),
    url(r'^upload$', views.book_upload, name='book-upload'),

    url(r'^change-thumbnail/$', views.book_cover_update, name='change-thumbnail'),
    url(r'^change-thumbnail/$', views.book_cover_update, name='change-thumbnail'),
    url(r'^general-object-delete/$', views.book_delete, name="general-object-delete"),
    url(r'^object-like-toggle/$', utils.object_like_toggle, name="object-like-toggle"),
    url(r'^object-dislike-toggle/$', utils.object_dislike_toggle, name="object-dislike-toggle"),
    url(r'^general-objects-loader/$', utils.objects_loader, name="general-objects-loader"),

    url(r'^comment-like-toggle/$', utils.general_comment_like_toggle, name='comment-like-toggle'),
    url(r'^comment-dislike-toggle/$', utils.general_comment_dislike_toggle, name='comment-dislike-toggle'),
    url(r'^general-comment-delete/$', utils.general_comment_delete, name='general-comment-delete'),
    url(r'^get-comment-form/$', utils.get_comment_form, name='get-comment-form'),
    url(r'^save-comment-changes/$', utils.save_comment_update, name='save-comment-changes'),
    url(r'^comment-counts/$', utils.get_comments_count, name='comments-count'),
    url(r'^general-comment-add/$', utils.general_comment_add, name='general-comment-add'),
    url(r'^general-comments-sorts/$', utils.general_comments_sort_or_load, name='general-comments-sort'),
    url(r'^general-comments-load/$', utils.general_comments_sort_or_load, name='general-comments-load'),

    url(r'^o-d-i/$', utils.object_download_count_increment, name='download-increment'),
    url(r'^o-v-i/$', utils.object_views_count_increment, name='views-increment'),
    url(r'^t-v-i/$', utils.tags_views_count_increment, name='tags-views-inc'),
    url(r'^tags-create/$', utils.tags_create, name="tags-create"),
    url(r'^add-tags-model/$', utils.add_tags_to_model, name="tags-to-model"),
    url(r'^u-f-t/$', utils.uploader_follow_toggle, name="uploader-follow-toggle"),

    url(r'^c-n-sp-sh/$', utils.create_spreadsheet, name="create-spreadsheet"),
    url(r'^spreadsheets-loader/$', utils.spreadsheets_loader, name="spreadsheets-loader"),
    url(r'^contributors-toggle/$', utils.contributors_toggle, name="contributors-toggle"),

    url(r'^(?P<username>[-\w]+)/spreadsheet=(?P<slug>[-\w]+)$', views.spreadsheet_detail, name='spreadsheet-detail'),
    url(r'^spreadsheet=(?P<slug>[-\w]+)/del/$', views.spreadsheet_delete, name='spreadsheet-delete'),
    url(r'^spreadsheet=(?P<slug>[-\w]+)/edit/$', views.spreadsheet_edit, name='spreadsheet-edit'),
    url(r'^(?P<username>[-\w]+)/spreadsheets$', views.spreadsheets_view, name='spreadsheets'),

    url(r'^spreadsheet=(?P<slug>[-\w]+)/lecture=(?P<lecture_id>[0-9]+)$', views.lecture_detail, name='lecture-detail'),
    url(r'^lecture=(?P<id>[0-9]+)/edit/$', views.lecture_edit, name='lecture-edit'),
    url(r'^lecture=(?P<id>[0-9]+)/del/$', views.lecture_delete, name='lecture-delete'),
    url(r'^lecture-create-ajax$', views.create_lecture, name='lecture-create'),

    url(r'^doctor/id=(?P<id>[0-9]+)/$', views.doctor_detail, name='doctor-detail'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<head>
    <title>{% block title %}{% endblock %} </title>
    <meta charset="UTF-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="{% trans 'description' %}" content="{% trans 'Basrah medical college, is social media, video, audio, books sharing and news publishing, free resources, free education' %}" >
    <meta name="{% trans 'keywords' %}" content="{% trans 'Basrah medical college, ask, social media, video, audio, book, news, posts, comments, pdf, message, resources, storage, upload, download, like, dislike, authors, chat, education' %}">
    <meta name="{% trans 'website' %}" content="{% trans 'Basrah medical college' %}">
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
{#    <script src="{% static 'js/jquery3.3.1.js' %}"></script>#}
    <link rel="stylesheet" href="{% static 'css/general-css-1210.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/responsive-css.-111233.css' %}" type="text/css">
    <link rel="shortcut icon" href="{% static 'img/cdn/website-logo.png' %}" type="image/x-icon">
</head>
<body style="background-color: teal">
<nav class="navbar navbar-expand-md bg-dark navbar-dark" style="z-index:2;width:100%;position:fixed;">
    <a class="navbar-brand" href="{% url 'book_app:home' %}">
           <img src="{% static 'img/cdn/website-logo.png' %}" alt="Logo" style="width:30px;height:30px;border-radius:5px;">
          <span class="responsive-text-16">{% trans 'Basrah Medical College' %}</span> </a>
  <button class="navbar-toggler responsive-text-15" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar" style="">
        <ul class="navbar-nav" >{% if request.user.is_superuser %}
            <li class="nav-item">
            <a class="nav-link responsive-text-16" href="{% url 'book_app:book-upload' %}">
                <span class="fa fa-plus"></span>
                {% trans 'Upload' %}
            </a>
            </li>{% endif %}
            <li class="nav-item">
            <a class="nav-link responsive-text-16" href="{% url 'account_app:uploaders' %}">
                <span class="fa fa-users"></span>
                {% trans 'Uploaders' %}</a>
            </li>
            <li class="nav-item">
            <a class="nav-link responsive-text-16" href="{% url 'book_app:liked-books' %}">
                <span class="fa fa-thumbs-up"></span>
                 {% trans 'Liked Books' %}
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link responsive-text-16" href="{% url 'notifications_app:home' %}">
                {% if unread_notifications > 0 %}
                <span class="notification-icons">{{ unread_notifications }}</span>
                {% endif %}
                <span class="fa fa-bell"></span>
            </a>
            </li>
            <!--- dropdown -->
            <li class="nav-item dropdown" >
             {% if request.user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    <img {% if user_profile.picture %}src="{{ user_profile.picture.url }}" {% else %}src="{{ user_profile.picture_cdn }}"{% endif %}  style="height:25px;width:25px;border-radius:3px;">
                    <span class="caret"></span>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item responsive-text-16" href="{% url 'account_app:profile' request.user %}"><span class="fa fa-user"></span> {% trans 'Profile' %}</a>
                    <a class="dropdown-item responsive-text-16" href="{% url 'account_app:account-edit' %}"><span class="fa fa-cog"></span> {% trans 'Settings' %}</a>
                    <a class="dropdown-item responsive-text-16" href="{% url 'account_app:logout' %}"><span class="fa fa-sign-out-alt"></span> {% trans 'Logout' %}</a>
                </div>
             {% else %}
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            {% trans 'Account' %}
            </a>
            <div class="dropdown-menu">
            <a class="dropdown-item responsive-text-16" href="{% url 'account_app:register' %}"><span class="fa fa-user-plus"></span> {% trans 'Sign Up' %}</a>
            <a class="dropdown-item responsive-text-16" href="{% url 'account_app:login' %}"><span class="fa fa-sign-in-alt"></span> {% trans 'Login' %}</a>
            </div>
             {% endif %}
            </li>
            <!--- dropdown -->
        </ul>
  </div>
</nav>
<div class="body-container" style="top:50px;width:100%;display:block;position:relative;margin:0;padding:10px;">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>