BMC/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url
from django.urls import path, include

app_name = 'BMC'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('a/', include('account.urls', namespace='account_app')),
    url(r'^', include('book.urls'), name='book_app'),
    url(r'^notifications/', include('notifications.urls', namespace='notifications_app')),

]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""BMC URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

book/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from book import views
from tools import utils
app_name = 'book_app'

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'^book_view=(?P<slug>[-\w]+)$', views.book_detail, name='book_detail'),
    url(r'^tags=(?P<slug>[-\w]+)$', views.view_by_tags, name='tags-view'),
    url(r'^category=(?P<category>[-\w]+)$', views.view_by_category, name='categories-view'),
    url(r'^book_view=(?P<slug>[-\w]+)/d/$', views.book_delete, name='book-delete'),
    url(r'^book_view=(?P<slug>[-\w]+)/e/$', views.book_edit, name='book-update'),
    url(r'^ajax-book-update/$', views.book_edit, name='ajax-book-update'),
    url(r'^liked_books$', views.liked_books, name='liked-books'),
    url(r'^upload$', views.book_upload, name='book-upload'),

    url(r'^change-thumbnail/$', views.book_cover_update, name='change-thumbnail'),
    url(r'^change-thumbnail/$', views.book_cover_update, name='change-thumbnail'),
    url(r'^general-object-delete/$', views.book_delete, name="general-object-delete"),
    url(r'^object-like-toggle/$', utils.object_like_toggle, name="object-like-toggle"),
    url(r'^object-dislike-toggle/$', utils.object_dislike_toggle, name="object-dislike-toggle"),
    url(r'^general-objects-loader/$', utils.objects_loader, name="general-objects-loader"),

    url(r'^comment-like-toggle/$', utils.general_comment_like_toggle, name='comment-like-toggle'),
    url(r'^comment-dislike-toggle/$', utils.general_comment_dislike_toggle, name='comment-dislike-toggle'),
    url(r'^general-comment-delete/$', utils.general_comment_delete, name='general-comment-delete'),
    url(r'^get-comment-form/$', utils.get_comment_form, name='get-comment-form'),
    url(r'^save-comment-changes/$', utils.save_comment_update, name='save-comment-changes'),
    url(r'^comment-counts/$', utils.get_comments_count, name='comments-count'),
    url(r'^general-comment-add/$', utils.general_comment_add, name='general-comment-add'),
    url(r'^general-comments-sorts/$', utils.general_comments_sort_or_load, name='general-comments-sort'),
    url(r'^general-comments-load/$', utils.general_comments_sort_or_load, name='general-comments-load'),

    url(r'^o-d-i/$', utils.object_download_count_increment, name='download-increment'),
    url(r'^o-v-i/$', utils.object_views_count_increment, name='views-increment'),
    url(r'^t-v-i/$', utils.tags_views_count_increment, name='tags-views-inc'),
    url(r'^tags-create/$', utils.tags_create, name="tags-create"),
    url(r'^add-tags-model/$', utils.add_tags_to_model, name="tags-to-model"),
    url(r'^u-f-t/$', utils.uploader_follow_toggle, name="uploader-follow-toggle"),

    url(r'^c-n-sp-sh/$', utils.create_spreadsheet, name="create-spreadsheet"),
    url(r'^spreadsheets-loader/$', utils.spreadsheets_loader, name="spreadsheets-loader"),
    url(r'^contributors-toggle/$', utils.contributors_toggle, name="contributors-toggle"),

    url(r'^(?P<username>[-\w]+)/spreadsheet=(?P<slug>[-\w]+)$', views.spreadsheet_detail, name='spreadsheet-detail'),
    url(r'^spreadsheet=(?P<slug>[-\w]+)/del/$', views.spreadsheet_delete, name='spreadsheet-delete'),
    url(r'^spreadsheet=(?P<slug>[-\w]+)/edit/$', views.spreadsheet_edit, name='spreadsheet-edit'),
    url(r'^(?P<username>[-\w]+)/spreadsheets$', views.spreadsheets_view, name='spreadsheets'),

    url(r'^spreadsheet=(?P<slug>[-\w]+)/lecture=(?P<lecture_id>[0-9]+)$', views.lecture_detail, name='lecture-detail'),
    url(r'^lecture=(?P<id>[0-9]+)/edit/$', views.lecture_edit, name='lecture-edit'),
    url(r'^lecture=(?P<id>[0-9]+)/del/$', views.lecture_delete, name='lecture-delete'),
    url(r'^lecture-create-ajax$', views.create_lecture, name='lecture-create'),

    url(r'^doctor/id=(?P<id>[0-9]+)/$', views.doctor_detail, name='doctor-detail'),

]

book/models.py
from django.utils.translation import ugettext as _
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from django.db.models import Q
from tools.categories import book_category, general_category, material_list
from tools.unique_url import random_unique_chars_digit_slug_generator
from datetime import datetime, time, timedelta, date


class CommentsManager(models.Manager):
    def sliced(self):
        return super(CommentsManager, self).all()[:5]


class BookManager(models.Manager):
    def search(self, query, category=None, type=None):
        if query and category == "General":
            qs = super(BookManager, self).filter(
                Q(description__icontains=query) |
                # Q(tags__icontains=query) |
                Q(title__icontains=query) |
                Q(user__username__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__contains=query)
            ).distinct()
            return qs
        elif query is not None and category != 'General':

            qs = super(BookManager, self).filter(
                Q(description__icontains=query) and Q(category__contains=category) |
                Q(tags__icontains=query) and Q(category__contains=category) |
                Q(title__icontains=query) and Q(category__contains=category) |
                Q(user__username__icontains=query) and Q(category__contains=category) |
                Q(user__first_name__icontains=query) and Q(category__contains=category) |
                Q(user__last_name__icontains=query)and Q(category__contains=category)
            ).distinct()
            return qs
        else:
            return None


class LectureManager(models.Manager):
    def search(self, query, material="General"):
        if query and material == "General":
            qs = super(LectureManager, self).filter(
                Q(comment__icontains=query) |
                Q(title__icontains=query) |
                Q(doctor__icontains=query) |
                Q(links__title__icontains=query)
            ).distinct()
            return qs

        elif query is not None and material != 'General':
            qs = super(LectureManager, self).filter(
                Q(comment__icontains=query) and Q(material__contains=material) |
                Q(title__icontains=query) and Q(material__contains=material) |
                Q(doctor__icontains=query) and Q(material__contains=material) |
                Q(links__title__icontains=query) and Q(material__contains=material)
            ).distinct()
            return qs
        else:
            return None

    def filter_by_date(self, material, from_date, to_date, *args, **kwargs):
        if material and from_date and to_date:

            s_year, s_month, s_day = from_date.split("-")
            e_year, e_month, e_day = to_date.split("-")
            start_date = datetime.combine(date(int(s_year), int(s_month), int(s_day)), time())
            end_date = datetime.combine(date(int(e_year), int(e_month), int(e_day)), time())
            qs = super(LectureManager, self).filter(timestamp__range=(start_date, end_date)).filter(
                material__exact=material
            )
            print("filter by date", qs)
            return qs
        else:
            pass


class BookTagsModel(models.Model):
    title = models.CharField(max_length=150, unique=False, db_index=True)
    slug = models.SlugField(_('Slug'), max_length=255, blank=True, unique=False)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    views = models.BigIntegerField(default=0, blank=True, null=True)
    type = models.CharField(max_length=10, null=True, blank=True, default="bk")
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title, allow_unicode=True)
        super(BookTagsModel, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_app:tags-view", kwargs={"slug": self.slug})


class BookModel(models.Model):
    title = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books")
    slug = models.SlugField(blank=True, editable=False, unique=True)
    like = models.ManyToManyField(User, related_name='book_likes', blank=True)
    dislike = models.ManyToManyField(User, related_name='book_dislike', blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to='books/cover')
    thumbnail_cdn = models.TextField(null=True, blank=True)
    file = models.FileField(blank=True, null=True, upload_to="books/pdf/")
    file_cdn = models.TextField(blank=True, null=True)
    category = models.CharField(max_length=100, choices=book_category, default='General')
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(BookTagsModel, related_name='tags', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)  # auto_now_add for creation date
    update = models.DateTimeField(auto_now=True)  # auto_now for update
    views = models.BigIntegerField(default=0, blank=True)
    share = models.BigIntegerField(default=0, blank=True)
    download = models.PositiveIntegerField(default=0, blank=True, null=True)
    download_link_1 = models.TextField(blank=True, null=True)
    download_link_2 = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=5, null=True, blank=True, default='bk')
    objects = models.Manager()
    manager = BookManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id', '-timestamp']

    def get_absolute_url(self):
        return reverse("book_app:book_detail", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("book_app:book-update", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("book_app:book-delete", kwargs={"slug": self.slug})

    def get_profile_url(self):
        return reverse("account_app:profile", kwargs={'username': self.user.username})


class BookCommentModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commentsmodel_set')
    slug = models.SlugField(blank=True, null=True, editable=False, unique=True)
    book = models.ForeignKey(BookModel, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField(max_length=1000)
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    dislike = models.ManyToManyField(User, related_name='dislikes', blank=True)
    type = models.CharField(max_length=5, null=True, blank=True, default='bk')
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    objects = CommentsManager()

    def get_profile_url(self):
        return reverse("account_app:profile", kwargs={'username': self.user.username})


class SpreadsheetModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='spreadsheets')
    slug = models.SlugField(blank=True, null=True, editable=False, unique=True)
    title = models.CharField(max_length=1000, blank=True, null=True)
    description = models.TextField(max_length=1000, blank=True, null=True)
    contributors = models.ManyToManyField(User, related_name='contributors', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    views = models.BigIntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_profile_url(self):
        return reverse("account_app:profile", kwargs={'username': self.user.username})

    def get_absolute_url(self):
        return reverse("book_app:spreadsheet-detail", kwargs={'username': self.user.username, 'slug': self.slug})


doctor_img_cdn = (
    ("/static/img/cdn/doctor-male.jpg", "Male"), ("/static/img/cdn/doctor-female.jpg", "Female")
)


class DoctorModel(models.Model):
    first_name = models.CharField(max_length=225)
    last_name = models.CharField(max_length=225, blank=True, null=True)
    surname = models.CharField(max_length=225, blank=True, null=True)
    picture = models.ImageField(blank=True, null=True)
    picture_cdn = models.CharField(choices=doctor_img_cdn, max_length=1000, blank=True, null=True)
    gender = models.CharField(choices=(("Male", "Male"), ("Female", "Female")), max_length=1000, default=1)
    description = models.TextField(max_length=1000, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    facebook = models.CharField(blank=True, null=True, max_length=10000)
    phone_no = models.IntegerField(blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("book_app:doctor-detail", kwargs={"id": self.id})

    def __str__(self):
        if self.last_name:
            second_name = self.last_name
            if self.surname:
                second_name = self.last_name + ' ' + self.surname
        elif self.surname:
            second_name = self.surname
            if self.last_name:
                second_name = self.last_name + ' ' + self.surname
        else:
            second_name = ""
        full_name = self.first_name + ' ' + second_name
        return full_name


class LectureModel(models.Model):
    material = models.CharField(choices=material_list, default=material_list[0], max_length=100)
    doctor = models.ForeignKey(DoctorModel, related_name='lectures', on_delete=False)

templates/book/includes/book-detail-urls-container.html
<script>

</script>
<script>
    $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}'}});
</script>

templates/book/includes/book-form-section.html
{% load i18n %}
<div class="card bg-basic" id="book-share-section" >
    <div class="main-loading-container" id="main_loading_container_id" style="display: none;">
        <div style="padding:5px;" class="uploaded-book-container" id="uploaded_book_container_id"></div>
        <div class="responsive-text-15" style="display: flex;justify-content: center;">
            <div class="alert alert-success" id="text_alert_id" style="margin-top:10px;">{% trans 'Please Wait' %}</div>
        </div>
        <div class="progress-container" id="progress_container_id" style="padding:15px;display: flex;justify-content: center;">
            <progress class="responsive-text-15" value="0" max="100" id="book_progress_id" style="width:100%; height:30px;display: inline-block"></progress>
            <div class="responsive-text-15" id="percent_id" style="padding:3px;background: red;color:white;">0%</div><br>
        </div>
    </div>
    <div class="main-book-form-container">
        <div class="card-body" id="main_book_form_container_id">
            <form method="post" id="book_form_id" enctype="multipart/form-data" >{% csrf_token %}
                <div class="forms-container" id="forms_container_id">
                    <div class="inputs-container">
                        {% for field in book_form %}
                                {% include "general/form-template.html" %}
                        {% endfor %}
                    </div>
                </div>
                <div class="tags-container"  id="main_tags_container_id">
                    {% include "general/main-tags-create-container.html" %}
                </div>
                <div class="btns-container" style="margin-top:15px;">
                    <div class="btn-group d-flex">
                        <button onclick="getBookForm()" style="display: none;" id="upload_again_btn_id" type="button" class="btn btn-primary w-100 responsive-text-15">
                            <span class="fa fa-upload"></span> {% trans 'Upload another book' %}
                        </button>
                        <button id="upload_btn_id" type="submit" class="btn btn-primary w-100 responsive-text-15">
                            <span class="fa fa-upload"></span> {% trans 'Upload' %}
                        </button>
                        <button type="reset" id="cancel_btn_id" class="btn btn-primary w-100 responsive-text-15">
                            <span class="fa fa-times"></span>
                            {% trans 'Cancel' %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

templates/book/includes/book-form-urls-container.html
{% load i18n %}
{% load staticfiles %}
<script>
    var __upload_book_url__ = "{% url 'book_app:book-upload' %}";
    var __upload_update_url__ = "{% url 'book_app:ajax-book-update' %}";
    var __change_thumbnail_url__ = "{% url 'book_app:change-thumbnail' %}";

</script>
<script>
    var uploading_canceled_text = "{% trans 'Uploading canceled' %}";
    var uploading_finished_text = "{% trans 'Uploading finished' %}";
    var uploading_started_text = "{% trans 'Uploading started, please wait' %}";
    var uploading_error_text = "{% trans 'Some errors happened, please try again' %}";
</script>

<script about="img-src">
    var __loader_progress_url__ = "{% static 'img/loaders/ajax-loader.gif' %}"
</script>
<script>
    $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}'}});
    var csrf_token = "{{ csrf_token }}";
</script>

templates/book/includes/book-main-urls-container.html
{% load i18n %}
{% load staticfiles %}
<script>
    var __objects_loader_url__ = "{% url 'book_app:spreadsheets-loader' %}";
    var __create_new_spreadsheet_url__ = "{% url 'book_app:create-spreadsheet' %}";
    var __contributors_toggle_url__ = "{% url 'book_app:contributors-toggle' %}";
    var __lecture_create_url__ = "{% url 'book_app:lecture-create' %}";
    var __object_views_increment_url__ = "{% url 'book_app:views-increment' %}";

</script>
<script>
    var uploading_canceled_text = "{% trans 'Uploading canceled' %}";
    var uploading_finished_text = "{% trans 'Uploading finished' %}";
    var uploading_started_text = "{% trans 'Uploading started, please wait' %}";
    var uploading_error_text = "{% trans 'Some errors happened, please try again' %}";
</script>

<script about="img-src">
    var __loader_progress_url__ = "{% static 'img/loaders/ajax-loader.gif' %}"
</script>
<script>
    $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}'}});
    var csrf_token = "{{ csrf_token }}";
</script>

templates/book/includes/books-loader.html
{% for book in objects %}
    {% include "book/includes/single-book-base-container.html" %}
{% endfor %}

templates/book/includes/category-queryset.html
{% for category in objects %}
    {% include "book/includes/single-category-base-container.html" %}
{% endfor %}

templates/book/includes/comment-update-form.html
{% load i18n %}
<form onsubmit="preventComFormDef(event, '{{ comment.id }}')" id="comment_form_updates_id{{ comment.id }}" method="post" action="" >{% csrf_token %}
    {{ book_comment_form.comment }}
    <div class="comments-btn-container">
        <div class="btn-group-sm d-flex">
            <button class="btn btn-primary" type="submit">
                <span class="fa fa-save"></span>
                <span class="responsive-text-15">{% trans 'Save' %}</span>
            </button>
        </div>
    </div>
</form>

templates/book/includes/comments-container.html
{% load i18n %}
<div class="book-comments-container">

    <div class="book-comment-sort-container" style="display: inline">
        <div class="responsive-text-15" style="float:right; "> {% trans 'Sort' %}:
            <select onchange="bookSortComments()" id="book_comments_sort_id" title="{% trans 'Sort the comments' %}">
                <option>{% trans 'Latest' %}</option>
                <option>{% trans 'Oldest' %}</option>
                <option>{% trans 'Most liked' %}</option>
                <option>{% trans 'Most disliked' %}</option>
            </select>
        </div>
    </div>
    <div class="comments-form-container">
        <div class="form-container" >
            <div class="comment-count-container">
                <span class="responsive-text-15"  style="font-size:15px;">{% trans 'Comments' %}: </span>
                <span class="comments-count" id="comment_count_id">{{ book.bookcommentmodel_set.count }}</span>
            </div>
            <div class="comment-form">
                <form  id="comment_form_id" method="post" action="" >{% csrf_token %}
                    {% if request.user.is_authenticated %}
                        {{ book_comment_form.comment }}
                    <div class="comments-btn-container">
                        <div class="btn-group-sm d-flex">
                            <button class="btn btn-primary" type="submit">
                                <span class="fa fa-comment"></span>
                                <span class="responsive-text-15">{% trans 'Comment' %}</span>
                            </button>
                            <button class="btn btn-primary" type="reset">
                                <span class="fa fa-window-close"></span>
                                <span class="responsive-text-15">{% trans 'Cancel' %}</span>
                            </button>
                        </div>
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    <div class="comments-text-container" id="comments_text_container_id" style="margin-top:20px;">
        {% for comment in comments %}
            {% include 'book/includes/comments-base.html' %}
        {% endfor %}
    </div>
</div>

templates/book/includes/lectures-queryset.html
{% for object in lectures %}
    {% include "book/includes/single-lecture-base-container.html" %}
{% endfor %}

templates/book/includes/single-book-base-container.html
{% load i18n %}
<div class="single-object-container sc" id="{{ book.slug }}_single_object_container_id" style="margin-bottom:10px;">
    <div class="card" >
        <div class="card-body" style="padding:10px;">
            <div class="book-title-container" style="margin-left:5px;">
                   <strong class="responsive-text-16"><a href="{{ book.get_absolute_url }}" class="card-link" style="color:black;">{{ book.title }}</a></strong>
            </div>
            <div class="book-img-container col-lg-2 col-md-2 col-sm-4" style="float:left;display:flex;justify-content: center">
                {% if book.thumbnail %}<a href="{{ book.get_absolute_url }}" >
                    <img src="{{ book.thumbnail.url }}" class="img-fluid" style="max-height:180px;max-width:250px;width:100%;border:1px outset silver;border-radius:5px;"/></a>
                {% else %}
                    <a href="{{ book.get_absolute_url }}" >
                    <img src="{{ book.thumbnail_cdn }}" class="img-fluid" style="max-height:180px;max-width:250px;width:100%;border:1px outset silver;border-radius:5px;"/></a>
                {% endif %}
            </div>
            <div class="boob-info-container col-lg-10 col-md-10 col-sm-12 responsive-text-12" style="float:right; ">
                <div class="library-container">
                   {% trans 'Uploader' %}: <a class="responsive-text-12" href="{% url 'account_app:profile' book.user %}"> {{ book.user.get_full_name }}</a>
                </div>{% if book.file %}
                <div class="size-container">
                    {% trans 'Size' %}: {{ book.file.size|filesizeformat }}
                </div>{% endif %}
                <div class="size-container">
                    {% trans 'Category' %}: <a href="{% url 'book_app:categories-view' book.category %}">{{ book.category }}</a>
                </div>
                <div class="timestamp-container">
                    {% trans 'Published on' %}: {{ book.timestamp|date }} ({{ book.timestamp|timesince }})
                </div>
                <div class="download-container">
                    {% trans 'Download' %}: {{ book.download }}
                </div>
                <div class="tags-container">{% if book.tags.all %}{% trans 'Tags' %}:
                    {% for tag in book.tags.all %}
                        <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
                    {% endfor %}{% endif %}
                </div>
                <div class="authors-container">{% if book.authors.all %}{% trans 'Authors' %}:
                    {% for author in book.authors.all %}
                       <a href="{{ author.get_absolute_url }}">{{ author.name }}</a>
                    {% endfor %}{% endif %}
                </div>
            </div>
            <div class="book-buttons-container col-lg-10 col-md-10 col-sm-12" style="float:right;">
                <div class="btn-group d-flex">
                    <a class="btn btn-primary w-100 responsive-text-13" style="padding:3px 0 3px 0;;" {% if book.file %} href="{{ book.file.url }}"{% else %} href="{{ book.file_cdn }}"{% endif %}  download="" target="_blank" onclick="bookDownloadFunc('{{ book.slug }}')" >
                        <span class="fa fa-download" ></span> {% trans 'Download' %}
                    </a>
                    <a class="btn btn-primary w-100 responsive-text-13" style="padding:3px 0 3px 0;" href="{{ book.get_absolute_url }}">
                        <span class="fa fa-eye" ></span> {% trans 'Preview' %}
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/book/includes/single-lecture-base-container.html
{% load i18n %}
<a href="{% url 'book_app:lecture-detail' slug=object.spreadsheet.slug lecture_id=object.id %}" class="single-object-container" id="{{ object.slug }}_single_object_container_id" style="text-decoration:none;margin-bottom:10px;display:block;color:black;">
    <div class="card">
        <div class="card-body" style="padding:10px;display:block;">
            <div class="book-title-container" style="display: block;">
                <strong class="responsive-text-16" >{{ object.title }}</strong>
            </div>
            <div class="doctor-container responsive-text-12" style="display: block">
                {% trans 'Doctor' %}: {{ object.doctor }}
            </div>
            <div class="doctor-container  responsive-text-12" >
                {% trans 'Material' %}: {{ object.material }}
            </div>
            <div class="boob-info-container  responsive-text-12" style=" ">
                 {% trans 'Published on' %}: {{ object.timestamp|date:"d/ m/ Y" }} ( {{ object.timestamp|timesince }} {% trans 'ago' %})
            </div>
        </div>
    </div>
</a>

templates/book/includes/single-spreadsheet-base-container.html
{% load i18n %}
<a href="{% url 'book_app:spreadsheet-detail' slug=object.slug username=object.user.username %}" class="single-object-container" id="{{ object.slug }}_single_object_container_id" style="margin-bottom:10px;display:block;color:black;">
    <div class="card">
        <div class="card-body" style="padding:10px;">
            <div class="book-title-container col-lg-9 col-sm-12" style="float:left;">
                <span class="fa fa-table"></span>
                <strong class="responsive-text-16" >{{ object.title }}</strong>
            </div>
            <div class="boob-info-container col-lg-3 col-sm-12 responsive-text-12" style="float:right; ">
                {{ object.timestamp|date:"d /m /Y" }} ( {{ object.timestamp|timesince}} {% trans 'ago' %})
            </div>
        </div>
    </div>
</a>

templates/book/includes/spreadsheets-queryset.html
{% for object in spreadsheets %}
    {% include "book/includes/single-spreadsheet-base-container.html" %}
{% endfor %}